name: github-action
description: A GitHub Action to run a Python script with a specific version of Python.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      -name: Install dependencies
        run: |
          make Install
      -name: lint
        run: |
          make Lint
      -name: test
        run: |
          make Test